// Stock data with company names, symbols, entry prices, dividend %, buy index, and risk index
export const stockData = [
  { name: "Conagra Brands", symbol: "CAG", entryPrice: 17, dividendPercent: 8.3, buyIndex: 7, riskIndex: 9 },
  { name: "Nestle", symbol: "NSRGY", entryPrice: 99, dividendPercent: 3.8, buyIndex: 3.5, riskIndex: 7 },
  { name: "Kraft Heinz", symbol: "KHC", entryPrice: 24.5, dividendPercent: 6.6, buyIndex: 4.5, riskIndex: 10 },
  { name: "General Mills", symbol: "GIS", entryPrice: 46, dividendPercent: 5.3, buyIndex: 7.5, riskIndex: 8 },
  { name: "Kellanova", symbol: "K", entryPrice: 83, dividendPercent: 2.7, buyIndex: 7, riskIndex: 5 },
  { name: "JM Smucker Company", symbol: "SJM", entryPrice: 107, dividendPercent: 4, buyIndex: 6, riskIndex: 8 },
  { name: "B&G Foods Inc", symbol: "BGS", entryPrice: 4.6, dividendPercent: 17, buyIndex: null, riskIndex: null },
  { name: "Hormel Food Corporation", symbol: "HRL", entryPrice: 22, dividendPercent: 5.2, buyIndex: 7, riskIndex: 9 },
  { name: "Bunge Limited", symbol: "BG", entryPrice: 95, dividendPercent: 3, buyIndex: 8, riskIndex: 5 },
  { name: "Hershey Co", symbol: "HSY", entryPrice: 169, dividendPercent: 3, buyIndex: 5, riskIndex: 8 },
  { name: "Mondelez International Inc", symbol: "MDLZ", entryPrice: 56, dividendPercent: 3.5, buyIndex: 5, riskIndex: 8 },
  { name: "Campbell Soup", symbol: "CPB", entryPrice: 31, dividendPercent: 5, buyIndex: 3, riskIndex: 8 },
  { name: "McCormick", symbol: "MKC", entryPrice: 64, dividendPercent: 3, buyIndex: 5, riskIndex: 9 },
  { name: "Walt Disney Company", symbol: "DIS", entryPrice: 112, dividendPercent: 0.9, buyIndex: 8, riskIndex: 7 },
  { name: "Conoco Phillips", symbol: "COP", entryPrice: 88, dividendPercent: 4, buyIndex: 9, riskIndex: 7 },
  { name: "Pfizer Inc", symbol: "PFE", entryPrice: 24.5, dividendPercent: 7, buyIndex: 8, riskIndex: 4.5 },
  { name: "Exxon Mobil Corp", symbol: "XOM", entryPrice: 120, dividendPercent: 3.5, buyIndex: 9, riskIndex: 6 },
  { name: "Ford Motor Company", symbol: "F", entryPrice: 13.5, dividendPercent: 4.6, buyIndex: 10, riskIndex: 6 },
  { name: "Altria Group", symbol: "MO", entryPrice: 58.5, dividendPercent: 7.37, buyIndex: 10, riskIndex: 5 },
  { name: "General Motors Company", symbol: "GM", entryPrice: 71.6, dividendPercent: 1, buyIndex: 10, riskIndex: 6 },
  { name: "Toyota Motor Corporation ADR", symbol: "TM", entryPrice: 206, dividendPercent: 2.7, buyIndex: 8, riskIndex: 6 },
  { name: "Honda Motor", symbol: "HMC", entryPrice: 30, dividendPercent: 3.6, buyIndex: 6, riskIndex: 6 },
  { name: "Stellantis", symbol: "STLA", entryPrice: 11, dividendPercent: 6, buyIndex: 7, riskIndex: 4 },
  { name: "Bank of America", symbol: "BAC", entryPrice: 54, dividendPercent: 2, buyIndex: 10, riskIndex: 4.5 },
  { name: "JP Morgan and Chase", symbol: "JPM", entryPrice: 317, dividendPercent: 2, buyIndex: 10, riskIndex: 4.5 },
  { name: "Wells Fargo & Company", symbol: "WFC", entryPrice: 87, dividendPercent: 2, buyIndex: 10, riskIndex: 4.5 },
  { name: "Citigroup Inc", symbol: "C", entryPrice: 101, dividendPercent: 2.4, buyIndex: 10, riskIndex: 5 },
  { name: "Prudential Finance", symbol: "PRU", entryPrice: 107, dividendPercent: 5, buyIndex: 9, riskIndex: 7 },
  { name: "Metlife", symbol: "MET", entryPrice: 77.5, dividendPercent: 3, buyIndex: 9, riskIndex: 7 },
  { name: "American International Group", symbol: "AIG", entryPrice: 76.5, dividendPercent: 2.3, buyIndex: 9, riskIndex: 6.5 },
  { name: "Principal Financial Group Inc", symbol: "PFG", entryPrice: 84, dividendPercent: 4, buyIndex: 9, riskIndex: 7 },
  { name: "Verizon", symbol: "VZ", entryPrice: 41, dividendPercent: 7, buyIndex: 8, riskIndex: 4.5 },
  { name: "AT&T Inc", symbol: "T", entryPrice: 25, dividendPercent: 4.5, buyIndex: 7.5, riskIndex: 4.5 },
  { name: "T Mobile", symbol: "TMUS", entryPrice: 211, dividendPercent: 2, buyIndex: 8.5, riskIndex: 5 },
  { name: "Comcast", symbol: "CMCSA", entryPrice: 27.5, dividendPercent: 5, buyIndex: 10, riskIndex: 10 },
];

